# Generated by Django 4.1.4 on 2023-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(default="/static/avatar.gif"),
            preserve_default=False,
        ),
    ]
