# Generated by Django 4.1.4 on 2023-01-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_thread_locked_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='locked_at',
            new_name='closed_at',
        ),
    ]
