# Generated by Django 4.1.4 on 2023-01-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="thread",
            name="slug",
        ),
    ]
