# Generated by Django 4.1.4 on 2023-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_thread_unique_together_remove_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='locked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
