# Generated by Django 4.1.4 on 2023-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_post_subtopic_thread_topic_remove_borrowing_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subtopic",
            name="name",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subtopic",
            name="slug",
            field=models.SlugField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thread",
            name="title",
            field=models.CharField(default="Title", max_length=150),
            preserve_default=False,
        ),
    ]
