# Generated by Django 4.1.4 on 2023-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_thread_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=1500),
        ),
    ]
