# Generated by Django 4.1.4 on 2023-01-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0009_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="author",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="thread",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="thread",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
