# Generated by Django 4.1.4 on 2023-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_thread_author_thread_created_at_alter_subtopic_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="subtopic",
            unique_together={("slug", "topic")},
        ),
    ]
