# Generated by Django 4.1.4 on 2023-01-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_subtopic_unique_together_subtopic_parent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtopic",
            old_name="parent",
            new_name="topic",
        ),
        migrations.AlterUniqueTogether(
            name="subtopic",
            unique_together={("slug", "topic")},
        ),
    ]
