# Generated by Django 4.1.4 on 2023-01-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtopic",
            name="description",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
