# Generated by Django 4.1.4 on 2023-01-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_subtopic_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtopic",
            name="description",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
