# Generated by Django 4.1.4 on 2023-01-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_subtopic_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterOrderWithRespectTo(
            name="post",
            order_with_respect_to="thread",
        ),
    ]
