# Generated by Django 4.1.4 on 2023-01-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_alter_post_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"get_latest_by": "pk", "ordering": ("pk",)},
        ),
    ]
