name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    name: E2E tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - run: cd forum
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      
      - name: Run E2E tests 🧪
        run: pytest
